package enums;

public enum TipoRetorno {
	URL, 
	MASSA,
	CORPO, 
	STATUS, 
	NOMEAPK, 
	DEVICEID, 
	URLAPPIUM,
	VERSAODOSO, 
	PACOTESTEPS,
	APPWAITACTIVITY, 
	CAMINHODASFEATURES,
	CAMINHOARQUIVORELATORIOXML,
	CAMINHOARQUIVORELATORIOJSON, 
	CAMINHODASFEATURESWEBMOBILE;
}